// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/flights": {
            "get": {
                "description": "get flights",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "flights"
                ],
                "summary": "Get list of flights",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/flights.Flight"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/flights/create": {
            "post": {
                "description": "Creates new flight profile",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "flights"
                ],
                "summary": "Creates flight",
                "parameters": [
                    {
                        "description": "Flight data",
                        "name": "flight",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/flights.CreateFlightReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Flight created"
                    },
                    "400": {
                        "description": "Invalid flight data"
                    }
                }
            }
        },
        "/api/v1/flights/search": {
            "get": {
                "description": "Retrieves a list of flights filtered by the provided search parameters.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "flights"
                ],
                "summary": "Search flights by parameters",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Origin location of the flight",
                        "name": "origin",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Destination location of the flight",
                        "name": "destination",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Departure date and time",
                        "name": "departure",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Arrival date and time",
                        "name": "arrival",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/flights.Flight"
                            }
                        }
                    },
                    "404": {
                        "description": "No flights found matching the search criteria"
                    }
                }
            }
        },
        "/api/v1/flights/{id}": {
            "get": {
                "description": "Gets flight details for a specific flight ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "flights"
                ],
                "summary": "Get flight by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Unique identifier of the flight",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/flights.Flight"
                        }
                    },
                    "404": {
                        "description": "Flight not found"
                    }
                }
            }
        },
        "/api/v1/flights/{id}/delete": {
            "delete": {
                "description": "Delete a flight by unique identifier",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "flights"
                ],
                "summary": "Delete flight",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Unique identifier of the flight",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Passenger deleted"
                    },
                    "404": {
                        "description": "Passenger not found"
                    }
                }
            }
        },
        "/api/v1/flights/{id}/update": {
            "post": {
                "description": "Update an existing flight's details.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "flights"
                ],
                "summary": "Update flight data",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Unique identifier of the flight",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Flight data",
                        "name": "flight",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/flights.Flight"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Flight updated"
                    },
                    "404": {
                        "description": "Flight not found"
                    }
                }
            }
        },
        "/api/v1/passengers": {
            "get": {
                "description": "get passengers",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "passengers"
                ],
                "summary": "Get list of passengers",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/passenger.Passenger"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/passengers/create": {
            "post": {
                "description": "Creates new passenger profile",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "passengers"
                ],
                "summary": "Creates passenger",
                "parameters": [
                    {
                        "description": "Passenger data",
                        "name": "passenger",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/passenger.CreatePassengerReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Passenger created"
                    },
                    "400": {
                        "description": "Invalid passenger data"
                    }
                }
            }
        },
        "/api/v1/passengers/{id}": {
            "get": {
                "description": "Gets passenger details for a specific passenger ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "passengers"
                ],
                "summary": "Get passenger by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Unique identifier of the passenger",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/passenger.Passenger"
                        }
                    },
                    "404": {
                        "description": "Missing required parameters"
                    }
                }
            }
        },
        "/api/v1/passengers/{id}/delete": {
            "delete": {
                "description": "Delete a passenger by their unique identifier",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "passengers"
                ],
                "summary": "Delete passenger",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Unique identifier of the passenger",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Passenger deleted"
                    },
                    "404": {
                        "description": "Passenger not found"
                    }
                }
            }
        },
        "/api/v1/passengers/{id}/update": {
            "post": {
                "description": "Update an existing passenger's details.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "passengers"
                ],
                "summary": "Update passenger data",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Unique identifier of the passenger",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User name",
                        "name": "name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User surname",
                        "name": "surname",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User email",
                        "name": "email",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User password",
                        "name": "password",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Passenger updated"
                    },
                    "404": {
                        "description": "Passenger not found"
                    }
                }
            }
        },
        "/api/v1/tickets": {
            "get": {
                "description": "get tickets",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tickets"
                ],
                "summary": "Get list of tickets",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/booking.Ticket"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/tickets/book": {
            "post": {
                "description": "Creates a new ticket booking for a flight.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "booking"
                ],
                "summary": "Book a new ticket",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Ticket ID",
                        "name": "ticketID",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Passenger ID",
                        "name": "passengerID",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Additional Information",
                        "name": "additionalInfo",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Ticket successfully booked"
                    },
                    "400": {
                        "description": "Invalid ticket data"
                    }
                }
            }
        },
        "/api/v1/tickets/create": {
            "post": {
                "description": "Creates new ticket",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tickets"
                ],
                "summary": "Creates ticket",
                "parameters": [
                    {
                        "description": "Ticket data",
                        "name": "flight",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/booking.CreateTicketReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Ticket created"
                    },
                    "400": {
                        "description": "Invalid ticket data"
                    }
                }
            }
        },
        "/api/v1/tickets/passenger/{id}": {
            "get": {
                "description": "Returns ticket details for a specific passenger ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tickets"
                ],
                "summary": "Get tickets for passenger by passenger_id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Unique identifier of the passenger",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/booking.Ticket"
                            }
                        }
                    },
                    "404": {
                        "description": "tickets not found"
                    }
                }
            }
        },
        "/api/v1/tickets/{id}": {
            "get": {
                "description": "Returns ticket details for a specific ticket ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tickets"
                ],
                "summary": "Get ticket by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Unique identifier of the ticket",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/booking.Ticket"
                        }
                    },
                    "404": {
                        "description": "ticket not found"
                    }
                }
            }
        },
        "/api/v1/tickets/{id}/delete": {
            "delete": {
                "description": "Deletes a ticket using the ticket ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tickets"
                ],
                "summary": "Delete a ticket",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Unique identifier of the ticket",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Ticket successfully deleted"
                    },
                    "404": {
                        "description": "Ticket not found"
                    }
                }
            }
        },
        "/api/v1/tickets/{id}/update": {
            "post": {
                "description": "Updates the details of a ticket using the ticket ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tickets"
                ],
                "summary": "Update ticket details",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Unique identifier of the ticket",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated ticket data",
                        "name": "ticket",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/booking.Ticket"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Ticket successfully updated"
                    },
                    "400": {
                        "description": "Invalid ticket data"
                    },
                    "404": {
                        "description": "Ticket not found"
                    }
                }
            }
        },
        "/api/v1/tickets/{ticketID}/cancel": {
            "post": {
                "description": "Cancels an existing ticket using the ticket ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "booking"
                ],
                "summary": "Cancel an existing ticket",
                "parameters": [
                    {
                        "type": "string",
                        "description": "The ID of the ticket to cancel",
                        "name": "ticketID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Ticket successfully cancelled"
                    },
                    "404": {
                        "description": "Ticket not found"
                    }
                }
            }
        },
        "/api/v1/{ticketID}/change": {
            "post": {
                "description": "Changes the flight associated with a ticket to a new flight using the ticket ID and new flight ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "booking"
                ],
                "summary": "Change the flight of a ticket",
                "parameters": [
                    {
                        "type": "string",
                        "description": "The ID of the ticket to update",
                        "name": "ticketID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "The new flight ID to associate with the ticket",
                        "name": "newFlightID",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Flight successfully changed for the ticket"
                    },
                    "400": {
                        "description": "Invalid parameters"
                    },
                    "404": {
                        "description": "Ticket not found or cannot change flight for a cancelled ticket"
                    }
                }
            }
        }
    },
    "definitions": {
        "booking.CreateTicketReq": {
            "type": "object",
            "properties": {
                "additional_info": {
                    "type": "string"
                },
                "arrival_time": {
                    "type": "string"
                },
                "departure_time": {
                    "type": "string"
                },
                "flight_id": {
                    "type": "string"
                },
                "passenger_id": {
                    "type": "string"
                },
                "seat_number": {
                    "type": "string"
                }
            }
        },
        "booking.Ticket": {
            "type": "object",
            "properties": {
                "additional_info": {
                    "type": "string"
                },
                "arrival_time": {
                    "type": "string"
                },
                "booking_time": {
                    "type": "string"
                },
                "departure_time": {
                    "type": "string"
                },
                "flight_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "passenger_id": {
                    "type": "string"
                },
                "seat_number": {
                    "type": "string"
                },
                "status": {
                    "description": "\"booked\", \"cancelled\", \"confirmed\"",
                    "type": "string"
                }
            }
        },
        "flights.CreateFlightReq": {
            "type": "object",
            "properties": {
                "airline": {
                    "type": "string"
                },
                "arrival": {
                    "type": "string"
                },
                "departure": {
                    "type": "string"
                },
                "destination": {
                    "type": "string"
                },
                "origin": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                }
            }
        },
        "flights.Flight": {
            "description": "Flight model for API response.",
            "type": "object",
            "properties": {
                "airline": {
                    "type": "string"
                },
                "arrival": {
                    "type": "string"
                },
                "departure": {
                    "type": "string"
                },
                "destination": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "origin": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                }
            }
        },
        "passenger.CreatePassengerReq": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                }
            }
        },
        "passenger.Passenger": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "number": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8010",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Flight Ticket Service",
	Description:      "API Server for booking flight tickets",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
